services:
  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/mysql

  tool:
    image: phpmyadmin:latest
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=user
      - PMA_PASSWORD=password
    ports:
      - "8001:80"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    volumes:
      - .:/app
    working_dir: /app
    command: ["air", "-c", ".air.toml"]
    depends_on:
      - db
    ports:
      - "8080:8080"